root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/monitoring24-dev ./cmd/server"
  bin = "./tmp/monitoring24-dev"
  full_bin = "./tmp/monitoring24-dev"
  delay = 300
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "vendor", ".git", "data"]
  exclude_file = []
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"

[log]
  time = true

[screen]
  clear_on_rebuild = true
